/********************************************************************
* S4KalTrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S4KalTrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS4KalTrackDict();
extern void G__cpp_setup_inheritanceS4KalTrackDict();
extern void G__cpp_setup_typetableS4KalTrackDict();
extern void G__cpp_setup_memvarS4KalTrackDict();
extern void G__cpp_setup_globalS4KalTrackDict();
extern void G__cpp_setup_memfuncS4KalTrackDict();
extern void G__cpp_setup_funcS4KalTrackDict();
extern void G__set_cpp_environmentS4KalTrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KalTrackDim.h"
#include "TKalDetCradle.h"
#include "TKalFilterCond.h"
#include "TKalTrack.h"
#include "TKalTrackSite.h"
#include "TKalTrackState.h"
#include "TVKalDetector.h"
#include "TVMeasLayer.h"
#include "TVTrackHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S4KalTrackDictLN_TClass;
extern G__linked_taginfo G__S4KalTrackDictLN_TBuffer;
extern G__linked_taginfo G__S4KalTrackDictLN_TMemberInspector;
extern G__linked_taginfo G__S4KalTrackDictLN_TObject;
extern G__linked_taginfo G__S4KalTrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S4KalTrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TObjArray;
extern G__linked_taginfo G__S4KalTrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S4KalTrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TCollection;
extern G__linked_taginfo G__S4KalTrackDictLN_TSeqCollection;
extern G__linked_taginfo G__S4KalTrackDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TAttElement;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__S4KalTrackDictLN_TVector3;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalMatrix;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalTrackSite;
extern G__linked_taginfo G__S4KalTrackDictLN_TVKalDetector;
extern G__linked_taginfo G__S4KalTrackDictLN_TVTrack;
extern G__linked_taginfo G__S4KalTrackDictLN_TMaterial;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalDetCradle;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalFilterCond;
extern G__linked_taginfo G__S4KalTrackDictLN_TAttLockable;
extern G__linked_taginfo G__S4KalTrackDictLN_TVKalSite;
extern G__linked_taginfo G__S4KalTrackDictLN_TVKalState;
extern G__linked_taginfo G__S4KalTrackDictLN_TVKalSystem;
extern G__linked_taginfo G__S4KalTrackDictLN_THelicalTrack;
extern G__linked_taginfo G__S4KalTrackDictLN_TStraightTrack;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalTrackState;
extern G__linked_taginfo G__S4KalTrackDictLN_TKalTrack;
extern G__linked_taginfo G__S4KalTrackDictLN_TVTrackHit;
extern G__linked_taginfo G__S4KalTrackDictLN_TVMeasLayer;

/* STUB derived class for protected member access */
