/********************************************************************
* S4KalmanDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S4KalmanDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS4KalmanDict();
extern void G__cpp_setup_inheritanceS4KalmanDict();
extern void G__cpp_setup_typetableS4KalmanDict();
extern void G__cpp_setup_memvarS4KalmanDict();
extern void G__cpp_setup_globalS4KalmanDict();
extern void G__cpp_setup_memfuncS4KalmanDict();
extern void G__cpp_setup_funcS4KalmanDict();
extern void G__set_cpp_environmentS4KalmanDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TKalMatrix.h"
#include "TVKalSite.h"
#include "TVKalState.h"
#include "TVKalSystem.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S4KalmanDictLN_TClass;
extern G__linked_taginfo G__S4KalmanDictLN_TBuffer;
extern G__linked_taginfo G__S4KalmanDictLN_TMemberInspector;
extern G__linked_taginfo G__S4KalmanDictLN_TObject;
extern G__linked_taginfo G__S4KalmanDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S4KalmanDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4KalmanDictLN_TObjArray;
extern G__linked_taginfo G__S4KalmanDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S4KalmanDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTlEdoublegRcLcLEMatrixCreatorsOp1;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTlEdoublegRcLcLEMatrixCreatorsOp2;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__S4KalmanDictLN_TVector3;
extern G__linked_taginfo G__S4KalmanDictLN_TKalMatrix;
extern G__linked_taginfo G__S4KalmanDictLN_TCollection;
extern G__linked_taginfo G__S4KalmanDictLN_TSeqCollection;
extern G__linked_taginfo G__S4KalmanDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__S4KalmanDictLN_TAttLockable;
extern G__linked_taginfo G__S4KalmanDictLN_TVKalSite;
extern G__linked_taginfo G__S4KalmanDictLN_TVKalState;
extern G__linked_taginfo G__S4KalmanDictLN_TVKalSystem;
extern G__linked_taginfo G__S4KalmanDictLN_TVKalSitecLcLEStType;

/* STUB derived class for protected member access */
