/********************************************************************
* S4UtilsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S4UtilsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS4UtilsDict();
extern void G__cpp_setup_inheritanceS4UtilsDict();
extern void G__cpp_setup_typetableS4UtilsDict();
extern void G__cpp_setup_memvarS4UtilsDict();
extern void G__cpp_setup_globalS4UtilsDict();
extern void G__cpp_setup_memfuncS4UtilsDict();
extern void G__cpp_setup_funcS4UtilsDict();
extern void G__set_cpp_environmentS4UtilsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TAttDrawable.h"
#include "TAttElement.h"
#include "TAttLockable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S4UtilsDictLN_TClass;
extern G__linked_taginfo G__S4UtilsDictLN_TBuffer;
extern G__linked_taginfo G__S4UtilsDictLN_TMemberInspector;
extern G__linked_taginfo G__S4UtilsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S4UtilsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4UtilsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S4UtilsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4UtilsDictLN_TAttDrawable;
extern G__linked_taginfo G__S4UtilsDictLN_TAttElement;
extern G__linked_taginfo G__S4UtilsDictLN_TAttLockable;

/* STUB derived class for protected member access */
