/********************************************************************
* S4GoemDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error S4GoemDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableS4GoemDict();
extern void G__cpp_setup_inheritanceS4GoemDict();
extern void G__cpp_setup_typetableS4GoemDict();
extern void G__cpp_setup_memvarS4GoemDict();
extern void G__cpp_setup_globalS4GoemDict();
extern void G__cpp_setup_memfuncS4GoemDict();
extern void G__cpp_setup_funcS4GoemDict();
extern void G__set_cpp_environmentS4GoemDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCircle.h"
#include "TCutCone.h"
#include "TCylinder.h"
#include "THelicalTrack.h"
#include "THype.h"
#include "TPlane.h"
#include "TStraightTrack.h"
#include "TTube.h"
#include "TVCurve.h"
#include "TVSolid.h"
#include "TVSurface.h"
#include "TVTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__S4GoemDictLN_TClass;
extern G__linked_taginfo G__S4GoemDictLN_TBuffer;
extern G__linked_taginfo G__S4GoemDictLN_TMemberInspector;
extern G__linked_taginfo G__S4GoemDictLN_TObject;
extern G__linked_taginfo G__S4GoemDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__S4GoemDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4GoemDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__S4GoemDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__S4GoemDictLN_TVector2;
extern G__linked_taginfo G__S4GoemDictLN_TVCurve;
extern G__linked_taginfo G__S4GoemDictLN_TCircle;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__S4GoemDictLN_TVector3;
extern G__linked_taginfo G__S4GoemDictLN_TVTrack;
extern G__linked_taginfo G__S4GoemDictLN_TVSurface;
extern G__linked_taginfo G__S4GoemDictLN_TCutCone;
extern G__linked_taginfo G__S4GoemDictLN_TCylinder;
extern G__linked_taginfo G__S4GoemDictLN_THelicalTrack;
extern G__linked_taginfo G__S4GoemDictLN_THype;
extern G__linked_taginfo G__S4GoemDictLN_TPlane;
extern G__linked_taginfo G__S4GoemDictLN_TStraightTrack;
extern G__linked_taginfo G__S4GoemDictLN_TVSolid;
extern G__linked_taginfo G__S4GoemDictLN_TTube;

/* STUB derived class for protected member access */
